
name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: q1
      id: q1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: q1
        setup-command: npm install
        command: npm test q1
        timeout: 10
        max-score: 4
    - name: q2
      id: q2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: q2
        setup-command: npm install
        command: npm test q2
        timeout: 10
        max-score: 4
    - name: q3
      id: q3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: q3
        setup-command: npm install
        command: npm test q3
        timeout: 10
        max-score: 4
    - name: q4
      id: q4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: q4
        setup-command: npm install
        command: npm test q4
        timeout: 10
        max-score: 4
    - name: q5
      id: q5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: q5
        setup-command: npm install
        command: npm test q5
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        Q1_RESULTS: "${{steps.q1.outputs.result}}"
        Q2_RESULTS: "${{steps.q2.outputs.result}}"
        Q3_RESULTS: "${{steps.q3.outputs.result}}"
        Q4_RESULTS: "${{steps.q4.outputs.result}}"
        Q5_RESULTS: "${{steps.q5.outputs.result}}"
      with:
        runners: q1,q2,q3,q4,q5
